### ISSUE TITLE
Support for python 3.6

### ISSUE THREAD

**Issue by OfekIshay** [alliedvision/VimbaPython#16] opened 2020-09-22 06:41 UTC
I have wanted to install this package on JetPack 4.2.2, that comes with python 3.6.9 and found that installing python 3.7 clashes with something in JetPack.

Would it be possible to have support for 3.6.9?

**Comment by mrkschnk** [comment] 2020-09-22 06:49
The Python API was designed for Python 3.7+, because of the use of typing.
Once you remove ": type" and "->", as well as all imports from typing and the decorator "@RuntimeTypeCheckEnable ()", it should work with Python 3.6, too. Also the install script (setup.py) needs to be adapted, because that checks the version of the Python interpreter.
Should be doable within a morning.

**Comment by NiklasKroeger-AlliedVision** [comment] 2020-09-28 11:50
In fact it is not strictly required for you to remove all the type hints. There is some support for them in Python3.6. The limiting factor in Python3.6 is the support for runtime evaluation of types ([Python 3.7 what's new - PEP 563](https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-pep563)). This means you could get VimbaPython running on Python3.6 by removing all uses of the `@RuntimeTypeCheckEnable()`, or by changing the definition of the decorator to simply do nothing ([comment out lines 60 to 63 in `runtime_type_check.py`](https://github.com/alliedvision/VimbaPython/blob/master/vimba/util/runtime_type_check.py#L60-L63). Additionally you have to adjust `setup.py` as already mentioned to allow installation for Python3.6.

However please note that this removes some safety that was included into VimbaPython with a purpose as it allows you to pass incorrect argument types around which can lead to hard to troubleshoot behavior. Especially in places where these arguments end up in call to our C layer. It will also lead to quite a few unit-tests of VimbaPython failing. Therefore support with such a modified version of VimbaPython will be much more difficult.

With that being said I will close the issue. If you have further questions feel free to comment here again or reopen the issue. Or even better if you have ideas how we could implement the current functionality of the `@RuntimeTypeCheckEnable()` decorator with Python3.6 we would be very interested in that!

**Closed** 2020-09-28 11:59 UTC

**Comment by cnavarrete** [comment] 2021-01-15 18:02
Does this trick still works on the 4.2 version?

**Comment by Teresa-AlliedVision** [comment] 2022-08-26 13:13
**runtime_type_check.py comment out:**
![runtime_type_check](https://user-images.githubusercontent.com/109134653/186910267-2e48ca1e-0170-4583-b2c9-5771a283fe66.png)
**Edit setup.py and install.sh**
Change Python version query to 3.6 or any comparisons with the minor version to 6.
