### ISSUE TITLE
Weird color and low fps.

### ISSUE THREAD

**Issue by NatePolizogo** [alliedvision/VimbaPython#25] opened 2020-11-06 09:38 UTC
I am trying to use the VimbaPythonAPI with an Allied Vision ALVIUM 1800 U-1236c color camera. I have 2 issues.
The main problem is that my image is greenish when I try to use an xml file (created with vimba viewer) to load_setting(), cause I don't want things like exposure and white balance to change.
The second problem is that i want to capture a frame rapidly because this camera is gonna be used in a moving vehicle. I am using the synchronous grab with the lowest timeout I could set (200ms) but it is not enough. The frames are blurry. The fps is low too. 

It would be helpful if someone helped me with these two problems.

**Comment by NiklasKroeger-AlliedVision** [comment] 2020-11-06 10:47
> my image is greenish when I try to use an xml file

Does this only happen if you load your settings from an xml file? One possible reason for unexpected colour tints in the recorded image is an incorrect White Balance. You can check this by using the Vimba Viewer to display the camera image and play around with the sliders in the "Color" tab:
![image](https://user-images.githubusercontent.com/61547504/98356464-ea31ab80-2023-11eb-8a03-a5fe1fbd0188.png)

I am under the impression that these settings should be stored in the xml file as well. If that is not the case you can however set the values you are happy with by accessing the corresponding camera features after you entered the camera context manager (`with cam:`). This can be done for example like this (values shown here result in a green tint for me, adjust accordingly):
```python
cam.BalanceRatioSelector.set('Red')
cam.BalanceRatioAbs.set(1.2) # Adjust the value for your red setting here
cam.BalanceRatioSelector.set('Blue')
cam.BalanceRatioAbs.set(1.3) # Adjust the value for your blue setting here
```

>  I am using the synchronous grab with the lowest timeout I could set (200ms) but it is not enough.

You will get *much* better performance by using the asynchronous grab procedure. Take a look at one of our examples using asynchronous image acquisition to get an idea of how it works:
- [`asynchronous_grab.py`](https://github.com/alliedvision/VimbaPython/blob/master/Examples/asynchronous_grab.py) - This one only shows the idea of using a function as frame callback that is called whenever a new frame was recorded. It demonstrates how you can access some frame data and how you requeue your frame after you are done processing it.
- [`asynchronous_grab_opencv.py`](https://github.com/alliedvision/VimbaPython/blob/master/Examples/asynchronous_grab_opencv.py) - This one is slightly more advanced and shows you how you can use opencv to display the frames that were acquired asynchronously. It is a good start if you want to take a look at visualising you recorded images.
- [`multithreading_opencv.py`](https://github.com/alliedvision/VimbaPython/blob/master/Examples/multithreading_opencv.py) - This one demonstrates thread synchronization and how you might want to copy image data from the callback thread to a different processing thread with thread safe objects.

I hope these are a good start for your further development. If you do have more concrete questions on how to use asynchronous acquisition for your particular use case feel free to comment further details.

I also hope that the White Balance solves your "greenish colour" issues. If that is not the case our support team might be the better place to get further help as this does not seem like a problem with VimbaPython in particular. You can contact them via [the form on our website](https://www.alliedvision.com/en/support/contact-support-and-repair.html).

**Comment by NatePolizogo** [comment] 2020-11-06 14:14
This happens all in any case. When I don't load settings from a file there is an auto balance done. The result is good but have a little taste of green. Although as I mentioned I don't wont the color of the camera to be variable for consistency. When I load my xml to vimba viewer it works fine for all settings (including white balance). The problem is while I try to load it to my script. On top of that i tried the code you propose but I get an error that  'Camera' object has no attribute 'BalanceRatioAbs'. Can you clarify how to use these functions or/and in which script they exist to study them. I provide my code too, to be more eazy for you to tell me my mistakes.
![Screenshot from 2020-11-06 16-08-51](https://user-images.githubusercontent.com/58054696/98375716-2cbaae80-204b-11eb-84a2-8e7c212a2267.png)

**Comment by NiklasKroeger-AlliedVision** [comment] 2020-11-06 14:42
> When I don't load settings from a file there is an auto balance done. The result is good but have a little taste of green. Although as I mentioned I don't wont the color of the camera to be variable for consistency.

What the Auto White Balance does is manipulate the values for `BalanceRatio` for the red and green channel. Once you have values for these channels you are happy with you can simply keep on using them. If you do turn the auto white balance off those values will stay the same and you should not have any problems with consistency.

> When I load my xml to vimba viewer it works fine for all settings (including white balance). The problem is while I try to load it to my script

This is very unexpected. The Vimba Viewer and VimbaPython use the same method for uploading an xml settings file to the camera as far as I am aware (direct access via the VimbaC function `VmbCameraSettingsLoad`). Are you certain you are loading the settings file you are using for tests in the VimbaViewer when running you script? Perhaps the xml file is loaded from an unexpected working directory and contains unexpected values because of that. It might make sense to write a small test where you print the value of some camera setting you know you changes when applying your xml file before loading the settings and after loading the settings to see they are applied correctly.

> I get an error that 'Camera' object has no attribute 'BalanceRatioAbs'

I tested this code with a Mako U camera. When that was released it might be that the feature had a different name. You can find out the name of the feature by checking in the VimbaViewer, but I assume the feature is now called `BalanceRatio`. To check this in the Vimba Viewer go to the `All` tab in the settings overview and check the available settings under `Controls -> Whitebalance`. Here you should see `BalanceRatio` or a feature with a similar name. By clicking on it the window below the tree view will show you some details regarding that feature, including the feature name (highlighted in the screenshot below - Use the feature name for your camera!) you could use to access the feature from Vimba Python.
![image](https://user-images.githubusercontent.com/61547504/98376748-37be1080-2044-11eb-8f2a-326173812a6e.png)

**Comment by NiklasKroeger-AlliedVision** [comment] 2020-11-23 08:42
It has been some time since there was any activity on this issue. As the experienced problem is also not caused by the VimbaPython API I will close this issue here. If you do still experience problems feel free to reopen the issue or 
 contact our support via [the form on our website](https://www.alliedvision.com/en/support/contact-support-and-repair.html). They have more experience with helping in these general camera questions and will most likely be able to help you better.

**Closed by NiklasKroeger-AlliedVision** 2020-11-23 08:42 UTC
